### PR TITLE
ci: include LICENSE in release artifacts

### LINKED ISSUE #5: Include `LICENSE` in release tarballs
I'm trying to create an archlinux package using the released tarballs, but these don't include the license.

The license is required according to the [wiki](https://wiki.archlinux.org/title/PKGBUILD#license):

> License families like BSD or **MIT** are, strictly speaking, not a single license and each instance requires a separate license file. In license variable refer to them using a common SPDX identifier (e.g. BSD-3-Clause or MIT), but then **provide the corresponding file as if it was a custom license**.

### PR DESCRIPTION
**Pull request by ValdezFOmar**
Closes #5

### CODE REVIEW

**Comment by ribru17** [comment]
Thank you! Though I am a bit confused on this. I just downloaded the 1.3.0 tarball and it included the `LICENSE` for me. Were you using a release before the license was added? Also this CI doesn't do the tarballs, it just compiles the source code for different platforms

**Comment by ribru17** [comment]
Oh unless you need the actual compiled tarball?

**Comment by ribru17** [comment]
Thanks!! I will draft a new release soon

**Comment by ValdezFOmar** [comment]
> Oh unless you need the license in the actual compiled tarball?

Just to clarify, yes, that's what I ment.

**Pull request merged**
